apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artis-sceptra-com-tls
spec:
  secretName: artis-sceptra-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: artis-sceptra.com
  dnsNames:
    - artis-sceptra.com
    - www.artis-sceptra.com